---
##########################
## Hadolint config file ##
##########################

failure-threshold: warning

ignored:
  - DL3013 # pin versions in pip
  - DL3018 # pin versions in apk
  - DL3048 # Invalid label key.
