name: VoiceCreate Publish Beta
on:
  push:
    branches:
    - 'beta/*'
    - 'topic/*'
jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
    - name: Prepare
      id: prep
      run: |
        GHCR_IMAGE="ghcr.io/camalot/voicecreate";
        BUILD_DATEZ="$(date +'%Y-%m-%dT%TZ%z' -u)";
        TAGSZ="${GHCR_IMAGE}:beta,${GHCR_IMAGE}:beta-${{ github.sha }}";
        echo BUILD_TAGS=${TAGSZ} >> $GITHUB_ENV;
        echo BUILD_DATE=${BUILD_DATEZ} >> $GITHUB_ENV;

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v2
    - name: Set up Docker Buildx
      id: buildx
      uses: docker/setup-buildx-action@v2

    - name: Login to GHCR
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ github.token }}

    - name: Build and Push GHCR
      id: docker_build
      uses: docker/build-push-action@v4
      with:
        push: true
        build-args: |
          PROJECT_NAME=VoiceCreate
          BUILD_VERSION=beta-${{ github.sha }}
          BUILD_REF=${{ github.ref }}
          BUILD_SHA=${{ github.sha }}
          BUILD_DATE=${{ env.BUILD_DATE }}
        tags: ${{ env.BUILD_TAGS }}
